version: "3.7"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_fast_api
    environment:
      - POSTGRES_USER=pttrns
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=garments-api
    ports:
      - "5432:5432"
    networks:
      - general

  pipeline-api:
    image: fast_api_demo:latest
    command: uvicorn src.main:app --workers 8 --host 0.0.0.0 --port 80 --timeout-keep-alive 600
    container_name: fast_api_container
    user: root
    build:
      context: C:\Projects\fast_api_demo_github
    working_dir: /home/ubuntu/fast_api_demo
    ports:
      - "5000:80"
    networks:
      - general
    volumes:
      - C:\Projects\fast_api_demo_github:/home/ubuntu/fast_api_demo

networks:
  general:
    name: general
    ipam:
      driver: default
